import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState} from '../src/state.js';
import {CONFIG,ENERGY_OFFERS,sceneY,MAPS,NODE_BY_ID,ZONES,SEQUENCE,FIRST_POSITIONS} from '../src/config.js';
import {act,currentNode,collectionTarget,migrateHorse,accessible,receiveOrder,tick,settle,rewardFor} from '../src/game-engine.js';
const start=()=>{const s=initialState();act(s,'start');return s;};
const ok=(s,a,d={})=>{const r=act(s,a,d);assert.equal(r.ok,true,`${a}: ${r.message}`);return r;};
function completeMap(s,map){ok(s,'map',{map});let n;let guard=0;while((n=currentNode(s))){assert.ok(guard++<400);ok(s,'node',{id:n.id});while(s.dialog)ok(s,'dialog',{skip:true});}}
test('exact budgets, operation counts, mandatory materials and chest budget',()=>{let main=0,side=0,chest=0;MAPS.forEach((m,i)=>{const budget=m.nodes.reduce((a,n)=>a+(n.segments?.reduce((a,b)=>a+b,0)||0),0);assert.equal(budget,ZONES[i].budget);assert.equal(m.nodes.reduce((a,n)=>a+(n.segments?.length||0),0),ZONES[i].ops);main+=budget;side+=m.branches.flat().reduce((a,n)=>a+(n.segments?.reduce((a,b)=>a+b,0)||0),0);chest+=m.nodes.filter(n=>n.type==='chest'&&n.kind==='energy').reduce((a,n)=>a+n.amount,0);if(i)assert.equal(m.nodes.filter(n=>n.type==='material').length,2);});assert.equal(main,7800);assert.equal(side,1800);assert.equal(chest,1200);});
test('17-point end-to-end, automatic horse award and manual portal installation; full side collection',()=>{const s=start();s.energy=20000;completeMap(s,0);assert.equal(s.story.length,1);for(let m=1;m<=5;m++){completeMap(s,m);assert.equal(s.map,m);assert.equal(s.story.length,1+m*3);assert.equal(s.horses.length,m);assert.equal(s.installed.length,m-1);assert.equal(s.repairs.length,m);if(m===5){assert.equal(s.story.length,16);assert.ok(rewardFor(s,'horses').ready);assert.equal(rewardFor(s,'story').ready,false);}for(let b=0;b<2;b++){ok(s,'branch',{branch:b});let n;while(n=currentNode(s))ok(s,'node',{id:n.id});ok(s,'branch',{branch:null});}ok(s,'map',{map:0});assert.ok(s.dialog);while(s.dialog)ok(s,'dialog',{skip:true});assert.equal(s.installed.length,m);}assert.equal(s.story.length,17);assert.equal(s.spent,9600);assert.equal(s.mementos.length,10);assert.equal(s.repairs.length,5);ok(s,'claim',{id:'story'});const coins=s.coins;assert.equal(act(s,'claim',{id:'story'}).ok,false);assert.equal(s.coins,coins);ok(s,'map',{map:0});assert.equal(s.dialog,null);});
test('skip repair story still requires explicit marker collection',()=>{const s=start();s.energy=10000;completeMap(s,0);ok(s,'map',{map:1});while(currentNode(s)?.step!==1){const n=currentNode(s);ok(s,'node',{id:n.id});while(s.dialog)ok(s,'dialog',{skip:true});}const n=currentNode(s);ok(s,'node',{id:n.id});ok(s,'dialog',{skip:true});assert.equal(s.repairs.length,0);assert.equal(s.story.length,2);assert.equal(s.prepared[n.id],true);ok(s,'node',{id:n.id});assert.equal(s.repairs.length,1);});
test('zero energy does not prevent free actions, insufficient energy is atomic',()=>{const s=start(),n=currentNode(s);s.energy=0;const before=JSON.stringify(s.stages);assert.equal(act(s,'node',{id:n.id}).needEnergy,true);assert.equal(JSON.stringify(s.stages),before);assert.equal(act(s,'map',{map:1}).ok,false);ok(s,'map',{map:0});});
test('segments survive serialization, reward chests are idempotent',()=>{let s=start();s.energy=10000;let n;while(!(n=currentNode(s)).segments||n.segments.length<2)ok(s,'node',{id:n.id});ok(s,'node',{id:n.id});assert.equal(s.stages[n.id],1);s=JSON.parse(JSON.stringify(s));ok(s,'node',{id:n.id});assert.equal(s.completed[n.id],true);completeMap(s,0);const c=MAPS[0].nodes.find(n=>n.type==='chest'&&n.p===1);ok(s,'node',{id:c.id});const energy=s.energy;assert.equal(act(s,'node',{id:c.id}).ok,false);assert.equal(s.energy,energy);});
test('draw batches atomic, restore results without reroll, no automatic free chain',()=>{let s=start();s.tickets=9;assert.equal(act(s,'draw',{count:10}).ok,false);assert.equal(s.tickets,9);s.tickets=100;ok(s,'draw',{count:10});assert.equal(s.sequence,10);assert.equal(s.tickets,90);assert.equal(act(s,'draw',{count:1}).ok,false);const rs=JSON.stringify(s.pendingBatch);s=JSON.parse(JSON.stringify(s));assert.equal(JSON.stringify(s.pendingBatch),rs);ok(s,'ackBatch');s.free=1;ok(s,'draw',{free:true});assert.equal(s.sequence,11);assert.equal(s.tickets,90);});
test('1000 partitions of one sequence are equivalent; all 25 by item 120; tail remains legal',()=>{const base=start();base.tickets=300;for(let i=0;i<12;i++){ok(base,'draw',{count:10});ok(base,'ackBatch');}assert.equal(base.toys.length,25);assert.equal(FIRST_POSITIONS.at(-1),120);for(let run=0;run<1000;run++){const s=start();s.tickets=300;let left=120,seed=run+17;while(left){seed=(seed*1664525+1013904223)>>>0;const n=[1,5,10][seed%3];const count=n<=left?n:1;ok(s,'draw',{count});ok(s,'ackBatch');left-=count;}for(const k of ['energy','coins','speed','tickets','duplicate','free','sequence'])assert.equal(s[k],base[k]);assert.deepEqual(s.toys,base.toys);}for(let i=0;i<18;i++){ok(base,'draw',{count:10});ok(base,'ackBatch');}assert.equal(base.sequence,300);assert.equal(base.toys.length,25);assert.ok(base.duplicate<CONFIG.duplicateThreshold);assert.ok(base.free<300);});
test('upstream order is idempotent; offline actions fail without mutation',()=>{const s=start();assert.equal(receiveOrder(s,'order-1',80).ok,true);const e=s.energy;assert.equal(receiveOrder(s,'order-1',80).ok,false);assert.equal(s.energy,e);s.online=false;assert.equal(act(s,'node',{id:currentNode(s).id}).ok,false);assert.equal(receiveOrder(s,'order-2',80).ok,false);assert.equal(s.energy,e);});
test('natural recovery respects cap, overflow and fresh timer after spending',()=>{const t=Date.now(),s=initialState(t);s.energy=140;s.lastRegen=t;tick(s,t+20*CONFIG.regenMs);assert.equal(s.energy,150);s.energy=180;tick(s,t+30*CONFIG.regenMs);assert.equal(s.energy,180);s.energy=100;s.lastRegen=t;tick(s,t+3*CONFIG.regenMs);assert.equal(s.energy,103);});
test('expiry allows current visit, settlement clears event resources once and preserves main rewards',()=>{const s=start();s.clockOffset=14*86400000;const n=currentNode(s);ok(s,'node',{id:n.id});assert.equal(receiveOrder(s,'late',80).ok,false);s.coins=23;s.tickets=10;s.toys=[0];ok(s,'leave');assert.equal(s.ended,true);assert.equal(s.tickets,0);assert.equal(s.toys.length,0);assert.equal(s.coins,23);assert.ok(s.settlement.pendingEnergy>0);const snap=JSON.stringify(s);settle(s);assert.equal(JSON.stringify(s),snap);});
test('reset produces genuine initial state',()=>{assert.deepEqual(initialState(1000),initialState(1000));});

test('every main and side path runs bottom to top; final story is terminal',()=>{for(const m of MAPS){for(const list of [m.nodes.filter(n=>n.type!=='chest'),...m.branches]){for(let i=1;i<list.length;i++)assert.ok(sceneY(list[i])<sceneY(list[i-1]),list[i].id);}if(m.id>0)assert.equal(m.nodes.filter(n=>n.type!=='chest').at(-1).step,2);}});
test('final dialogue grants horse without further click, stays in zone, no duplicate on reload',()=>{const s=start();s.energy=20000;completeMap(s,0);ok(s,'map',{map:1});while(currentNode(s)?.step!==2){ok(s,'node',{id:currentNode(s).id});while(s.dialog)ok(s,'dialog',{skip:true});}const n=currentNode(s);ok(s,'node',{id:n.id});assert.equal(s.horses.length,0);const r=ok(s,'dialog',{skip:true});assert.equal(r.horse,true);assert.deepEqual(s.horses,[1]);assert.equal(s.story.length,4);assert.equal(s.map,1);assert.equal(currentNode(s),undefined);assert.equal(act(s,'node',{id:n.id}).ok,false);const restored=JSON.parse(JSON.stringify(s));migrateHorse(restored);assert.equal(restored.horses.length,1);assert.equal(restored.installed.length,0);});
test('old save waiting for horse pickup migrates once',()=>{const s=start(),n=MAPS[1].nodes.find(n=>n.step===2);s.map=1;s.prepared[n.id]=true;migrateHorse(s);assert.deepEqual(s.horses,[1]);assert.equal(s.completed[n.id],true);const tickets=s.tickets;migrateHorse(s);assert.equal(s.tickets,tickets);});
test('manual target follows nearest outstanding prerequisite including locked branch',()=>{const s=start();s.energy=20000;completeMap(s,0);ok(s,'map',{map:1});const horse=MAPS[1].nodes.find(n=>n.step===2);assert.equal(collectionTarget(s,horse.id).id,currentNode(s).id);const memo=MAPS[1].branches[0].at(-1);assert.equal(collectionTarget(s,memo.id).id,currentNode(s).id);while(!s.story.includes(2)){ok(s,'node',{id:currentNode(s).id});while(s.dialog)ok(s,'dialog',{skip:true});}assert.equal(collectionTarget(s,memo.id).id,MAPS[1].branches[0][0].id);});
test('both energy offers check balances and share limit without partial debit',()=>{const s=start();let e=s.energy;ok(s,'exchange',{offer:'small'});assert.equal(s.energy,e+40);assert.equal(s.diamonds,88);ok(s,'exchange',{offer:'large'});assert.equal(s.energy,e+140);assert.equal(s.diamonds,58);s.diamonds=11;const before=s.energy;assert.equal(act(s,'exchange',{offer:'small'}).ok,false);assert.equal(s.energy,before);assert.equal(s.diamonds,11);s.diamonds=1000;for(let i=0;i<3;i++)ok(s,'exchange',{offer:'small'});assert.equal(act(s,'exchange',{offer:'large'}).ok,false);assert.equal(act(s,'exchange',{offer:'invalid'}).ok,false);});
