import test from 'node:test';
import assert from 'node:assert/strict';
import {CONFIG,LOOP,MAPS,NODE_BY_ID,MANUAL_ITEMS,TASKS,TOYS,GACHA_ROOMS,GACHA_TAIL,STORY_REWARD,MANUAL_REWARD} from '../src/config.js';
import {initialState,migrateState,loadState,V15_SAVE_KEY} from '../src/state.js';
import {act,currentNode,rewardFor,completedCollections,settle,receiveOrder,tick,activityDay,eligible,activeOffers} from '../src/game-engine.js';
import {roomOrder} from '../src/gacha.js';
import {visibleNodes,guideGeometry,collectionChanges} from '../src/map-view.js';
const ok=(s,a,d={})=>{const r=act(s,a,d);assert.equal(r.ok,true,`${a}: ${r.message}`);return r;};
const start=()=>{const s=initialState();ok(s,'start');s.tutorial=4;return s;};
test('manual has five three-item regions and one five-horse collection with distinct sources',()=>{assert.equal(MANUAL_ITEMS.length,20);assert.equal(TASKS.length,6);assert.equal(TASKS.find(t=>t.id==='horses').total,5);assert.ok(TASKS.filter(t=>t.id!=='horses').every(t=>t.total===3&&t.items.length===3));assert.equal(new Set(MANUAL_ITEMS.map(i=>i.id)).size,20);assert.ok(MANUAL_ITEMS.every(i=>NODE_BY_ID[i.nodeId]));assert.deepEqual(MANUAL_REWARD,{wild:1});});
test('first and second copy inside one batch have different new/duplicate results',()=>{const s=start();s.tickets=100;let found=false;for(let seed=1;seed<100&&!found;seed++){s.gacha.seed=seed;const toys=roomOrder(seed,0).slice(0,10).filter(r=>r.type==='toy').map(r=>r.id);found=new Set(toys).size<toys.length;}assert.ok(found);const r=ok(s,'draw',{count:10}),seen=new Set();for(const result of r.results.filter(r=>r.type==='toy')){assert.equal(result.duplicate,seen.has(result.id));seen.add(result.id);}assert.equal(s.toys.length,seen.size);});
function step(s){if(s.dialog)return ok(s,'dialog',{skip:true});const n=currentNode(s);if(!n)return;return ok(s,n.type==='story'&&n.step===1&&!s.prepared[n.id]?'submit':'node',{id:n.id});}
function until(s,stop){for(let i=0;i<1000;i++){if(stop(s))return;assert.ok(currentNode(s)||s.dialog,'No reachable target');step(s);}throw Error('Progress exceeded guard');}
function full(s){s.energy=40000;until(s,s=>s.story.length===1);for(let m=1;m<=5;m++){ok(s,'map',{map:m});until(s,s=>s.horses.includes(m));ok(s,'map',{map:0});while(s.dialog)step(s);}}
test('insufficient energy and preview do not spend or advance',()=>{const s=start();s.energy=0;s.lastRegen=Date.now();const n=currentNode(s),before=structuredClone(s);assert.equal(act(s,'node',{id:n.id}).needEnergy,true);assert.deepEqual(s.stages,before.stages);assert.equal(s.dropSeed,before.dropSeed);const box=MAPS[0].nodes.find(n=>n.type==='chest');assert.equal(act(s,'node',{id:box.id}).ok,false);assert.equal(s.energy,0);});
test('each obstacle segment drops tickets once and survives serialization',()=>{let s=start();s.energy=3000;until(s,s=>currentNode(s)?.segments?.length===2);const n=currentNode(s),tickets=s.tickets;const r=ok(s,'node',{id:n.id});assert.ok(r.drop>=1);assert.equal(s.tickets,tickets+r.drop);s=JSON.parse(JSON.stringify(s));const r2=ok(s,'node',{id:n.id});assert.ok(r2.drop>=1);const after=s.tickets;assert.equal(act(s,'node',{id:n.id}).ok,false);assert.equal(s.tickets,after);});
test('all local map chests preview while future obstacles remain concealed',()=>{const s=start();s.energy=20000;until(s,s=>s.story.length===1);ok(s,'map',{map:1});const visible=visibleNodes(s);assert.equal(visible.filter(n=>n.type==='chest').length,6);assert.ok(!visible.some(n=>n.type==='story'&&n.step===2));assert.equal(guideGeometry(s).target.p,2);});
test('map switching cannot access a locked zone and never spends energy',()=>{const s=start(),e=s.energy;assert.equal(act(s,'map',{map:2}).ok,false);ok(s,'map',{map:0});assert.equal(s.energy,e);assert.equal(act(s,'branch',{branch:LOOP.branch}).ok,false);});
test('material repair requires confirmation; P06 requires the configured collection click',()=>{const s=start();s.energy=20000;until(s,s=>s.story.length===1);ok(s,'map',{map:1});until(s,s=>!s.dialog&&currentNode(s)?.step===1);assert.equal(s.dialog,null);assert.equal(act(s,'node',{id:currentNode(s).id}).ok,false);step(s);assert.equal(s.dialog.p,3);step(s);assert.ok(s.story.includes(3));assert.ok(s.manual.includes('oven'));until(s,s=>s.horses.includes(1));ok(s,'map',{map:0});while(s.dialog)step(s);ok(s,'map',{map:2});until(s,s=>!s.dialog&&currentNode(s)?.step===1);step(s);step(s);assert.ok(!s.story.includes(6));assert.ok(!s.manual.includes('tracks'));step(s);assert.ok(s.story.includes(6));assert.ok(s.manual.includes('tracks'));});
test('horse requires explicit receipt and manual total prize is independent of P17',()=>{const s=start();s.energy=40000;until(s,s=>s.story.length===1);for(let m=1;m<=5;m++){ok(s,'map',{map:m});until(s,s=>!s.dialog&&currentNode(s)?.step===2&&s.prepared[currentNode(s).id]);assert.equal(s.horses.length,m-1);assert.equal(s.story.length,3*m);step(s);assert.equal(s.map,m);assert.equal(s.story.length,1+3*m);if(m===5){assert.equal(completedCollections(s),6);assert.ok(!rewardFor(s,'story').ready);ok(s,'claim',{id:'manual-all'});assert.equal(s.wild,1);assert.equal(s.inbox.filter(x=>x.type==='wild').length,1);assert.equal(act(s,'claim',{id:'manual-all'}).ok,false);}ok(s,'map',{map:0});while(s.dialog)step(s);}assert.equal(s.story.length,17);assert.deepEqual(rewardFor(s,'story').reward,STORY_REWARD);ok(s,'claim',{id:'story'});assert.ok(s.inbox.some(i=>i.type==='starPack'));});
test('final-area loop unlocks after ending, repeats only its own objects and saves mid-round',()=>{let s=start();assert.equal(act(s,'branch',{branch:2}).ok,false);full(s);const story=[...s.story],manual=[...s.manual];ok(s,'map',{map:5});ok(s,'branch',{branch:2});step(s);s=JSON.parse(JSON.stringify(s));assert.equal(s.stages['loop-5-0'],1);until(s,s=>s.loopRound===1);assert.equal(currentNode(s).id,'loop-5-0');assert.equal(act(s,'node',{id:'loop-5-reward'}).ok,false);until(s,s=>s.loopRound===2);assert.deepEqual(s.story,story);assert.deepEqual(s.manual,manual);ok(s,'branch',{branch:null});assert.equal(s.branch,null);});
test('all four multipliers consume N tickets per result and insufficient batch stays atomic',()=>{for(const count of [1,3,5,10]){const s=start();s.tickets=200;const r=ok(s,'draw',{count});assert.equal(s.tickets,200-count*CONFIG.ticketCost);assert.equal(r.results.length,count);assert.equal(s.sequence,count);const snapshot=structuredClone(s);assert.equal(act(s,'draw',{count:1}).ok,false);assert.deepEqual(s.pendingBatch,snapshot.pendingBatch);}const s=start();s.tickets=2;const before=structuredClone(s);assert.equal(act(s,'draw',{count:3}).ok,false);assert.deepEqual(s.gacha,before.gacha);assert.equal(s.tickets,2);assert.equal(act(s,'draw',{free:true}).ok,false);});
test('same-batch duplicate converts immediately by quality and keeps exactly one ownership',()=>{const s=start();s.tickets=100;const order=roomOrder(s.gacha.seed,0);const toy=order.find(r=>r.type==='toy');s.toys=TOYS.map(t=>t.id);const e=s.energy;const r=ok(s,'draw',{count:10});const expected=r.results.reduce((a,r)=>a+(r.type==='toy'?CONFIG.duplicateEnergy[TOYS[r.id].q]:r.type==='energy'?r.amount:0),0);assert.equal(s.energy,e+expected);assert.equal(new Set(s.toys).size,25);assert.equal(s.free,0);assert.equal(s.duplicate,0);assert.ok(toy);});
test('pending batch recovery preserves results and does not re-deduct tickets',()=>{let s=start();s.tickets=100;ok(s,'draw',{count:10});const result=JSON.stringify(s.pendingBatch);s=JSON.parse(JSON.stringify(s));assert.equal(JSON.stringify(s.pendingBatch),result);const e=s.energy;ok(s,'ackBatch');assert.equal(s.tickets,90);assert.equal(s.energy,e);});
test('1000 room seeds: no replacement, batch partitions equivalent, all25 in4 rooms, tail continues',()=>{const variants=new Set();for(let seed=1;seed<=1000;seed++){const a=start(),b=start();a.tickets=b.tickets=500;a.gacha.seed=b.gacha.seed=seed;for(let room=0;room<4;room++){const order=roomOrder(seed,room);assert.equal(order.length,30);assert.equal(new Set(order.map(r=>r.slot)).size,30);}variants.add(roomOrder(seed,0).slice(0,3).map(r=>r.slot).join(','));for(let i=0;i<12;i++){ok(a,'draw',{count:10});ok(a,'ackBatch');}let left=120;while(left){const count=[1,3,5,10].find(n=>n<=left&&((left+seed)%n===0))||1;ok(b,'draw',{count});ok(b,'ackBatch');left-=count;}assert.equal(a.toys.length,25);for(const k of ['energy','coins','mainEnergy','speed','tickets','sequence'])assert.equal(a[k],b[k]);assert.deepEqual(a.toys,b.toys);assert.deepEqual(a.gacha,b.gacha);ok(a,'draw',{count:10});assert.equal(a.gacha.room,4);assert.equal(a.pendingBatch.results.length,10);}assert.ok(variants.size>900);});
test('room transition inside a ten-draw batch uses remaining slots before next room',()=>{const s=start();s.tickets=100;s.gacha.cursor=27;const r=ok(s,'draw',{count:10});assert.deepEqual(r.results.map(r=>r.room),[0,0,0,1,1,1,1,1,1,1]);assert.equal(s.gacha.cursor,7);});
test('invalid reward config rejects a batch before ticket or room mutation',()=>{const s=start();s.tickets=100;const original=GACHA_ROOMS[0][0];GACHA_ROOMS[0][0]={type:'bad',amount:2};s.gacha.cursor=roomOrder(s.gacha.seed,0).findIndex(r=>r.slot===0);const before=structuredClone(s);assert.equal(act(s,'draw',{count:1}).ok,false);assert.equal(s.tickets,before.tickets);assert.deepEqual(s.gacha,before.gacha);GACHA_ROOMS[0][0]=original;});
test('eligibility and switches: level7/wave6, soft keeps started period, hard blocks reentry',()=>{const s=initialState();s.profile.level=6;assert.equal(act(s,'start').ok,false);s.profile.level=7;s.profile.orders=5;assert.equal(act(s,'start').ok,false);s.profile.orders=6;s.feature='soft';assert.equal(act(s,'start').ok,false);s.feature='open';ok(s,'start');s.feature='soft';ok(s,'leave');ok(s,'enter');s.feature='hard';ok(s,'leave');assert.equal(act(s,'enter').ok,false);});
test('daily reset is03:00 atconfiguredtimezone, natural regen caps while reward overflow stays',()=>{const s=initialState();s.clockOffset=Date.parse('2026-09-23T02:59:00+08:00')-Date.now();const day=activityDay(s);s.clockOffset+=120000;assert.equal(activityDay(s),day+1);const t=Date.now(),a=initialState(t);a.energy=140;tick(a,t+20*CONFIG.regenMs);assert.equal(a.energy,150);a.energy=180;tick(a,t+30*CONFIG.regenMs);assert.equal(a.energy,180);});
test('settlement excludes map chests and activityenergy, includes qualified manual and toy rewards',()=>{const s=start();full(s);s.toys=TOYS.map(t=>t.id);const e=s.energy,c=s.coins;ok(s,'claim',{id:'region-1'});const expected={};for(const id of [...TASKS.map(t=>t.id),'manual-all','story','collection',...Array.from({length:5},(_,q)=>`quality-${q}`)]){if(s.claims.includes(id))continue;for(const [k,v]of Object.entries(rewardFor(s,id).reward))if(k!=='energy')expected[k]=(expected[k]||0)+v;}s.clockOffset=CONFIG.days*86400000+1000;ok(s,'leave');assert.equal(s.energy,0);assert.equal(s.tickets,0);assert.deepEqual(s.settlement.mailed,expected);assert.equal(s.coins,c+TASKS.find(t=>t.id==='region-1').reward.coins);assert.equal(s.settlement.claimed,false);const copy=JSON.stringify(s);settle(s);assert.equal(JSON.stringify(s),copy);ok(s,'claimSettlement');assert.equal(s.settlement.claimed,true);const after=JSON.stringify(s);assert.equal(act(s,'claimSettlement').ok,false);assert.equal(JSON.stringify(s),after);assert.ok(e>0);});
test('offline cannot settle and expiry allows current activity but refuses external supplies',()=>{const s=start();s.clockOffset=CONFIG.days*86400000+1000;s.online=false;assert.equal(settle(s).ok,false);assert.equal(s.ended,false);s.online=true;step(s);assert.equal(receiveOrder(s,'late',80).ok,false);assert.equal(act(s,'exchange',{offer:'small'}).ok,false);ok(s,'map',{map:0});assert.equal(s.ended,false);ok(s,'leave');assert.equal(s.ended,true);});
test('old save migration preserves progress and claims, converts only earned free draws to tickets',()=>{const old=start();old.schema=2;old.energy=999;old.free=3;old.duplicate=7;old.tickets=11;old.story=[1];old.claims=['quality-0'];old.toys=[0,1];delete old.gacha;const s=migrateState(old);assert.equal(s.schema,3);assert.equal(s.energy,999);assert.equal(s.tickets,14);assert.equal(s.free,0);assert.equal(s.migration.oldDuplicate,7);assert.deepEqual(s.toys,[0,1]);assert.deepEqual(s.claims,['quality-0']);assert.deepEqual(migrateState(s),s);assert.equal(loadState({getItem:k=>k===V15_SAVE_KEY?JSON.stringify(old):null}).schema,3);});
test('reward ids validated, grants once, earned toys NEW cleared only oncollection exit',()=>{const s=start();assert.equal(act(s,'claim',{id:'quality-99'}).ok,false);s.toys=[0,1,2,3,4];s.newToys=[0,1];ok(s,'claim',{id:'quality-0'});assert.equal(act(s,'claim',{id:'quality-0'}).ok,false);ok(s,'viewCollection');assert.deepEqual(s.newToys,[]);});
test('unconfigured commercialization hidden, reset deterministic, collection feedback excludes repeats',()=>{const s=start();assert.deepEqual(activeOffers(s),[]);assert.deepEqual(initialState(1000),initialState(1000));const after=structuredClone(s);after.manual=[TASKS[0].items[0].id];assert.equal(collectionChanges(s,after).length,1);assert.deepEqual(collectionChanges(after,after),[]);});
