import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,migrateState,loadState,SAVE_KEY,LEGACY_SAVE_KEY} from '../src/state.js';
import {CONFIG,ENERGY_OFFERS,sceneY,MAPS,NODE_BY_ID,ZONES,SEQUENCE,FIRST_POSITIONS,TASKS,MANUAL_ITEMS} from '../src/config.js';
import {act,currentNode,collectionTarget,resumeScene,taskCount,completedCollections,accessible,receiveOrder,tick,settle,rewardFor} from '../src/game-engine.js';
const start=()=>{const s=initialState();act(s,'start');return s;};
const ok=(s,a,d={})=>{const r=act(s,a,d);assert.equal(r.ok,true,`${a}: ${r.message}`);return r;};
function completeMap(s,map){ok(s,'map',{map});let n;let guard=0;while((n=currentNode(s))){assert.ok(guard++<400);ok(s,'node',{id:n.id});while(s.dialog)ok(s,'dialog',{skip:true});}}
test('zero energy does not prevent free actions, insufficient energy is atomic',()=>{const s=start(),n=currentNode(s);s.energy=0;const before=JSON.stringify(s.stages);assert.equal(act(s,'node',{id:n.id}).needEnergy,true);assert.equal(JSON.stringify(s.stages),before);assert.equal(act(s,'map',{map:1}).ok,false);ok(s,'map',{map:0});});
test('segments survive serialization, reward chests are idempotent',()=>{let s=start();s.energy=10000;let n;while(!(n=currentNode(s)).segments||n.segments.length<2)ok(s,'node',{id:n.id});ok(s,'node',{id:n.id});assert.equal(s.stages[n.id],1);s=JSON.parse(JSON.stringify(s));ok(s,'node',{id:n.id});assert.equal(s.completed[n.id],true);completeMap(s,0);const c=MAPS[0].nodes.find(n=>n.type==='chest'&&n.p===1);ok(s,'node',{id:c.id});const energy=s.energy;assert.equal(act(s,'node',{id:c.id}).ok,false);assert.equal(s.energy,energy);});
test('draw batches atomic, restore results without reroll, no automatic free chain',()=>{let s=start();s.tickets=9;assert.equal(act(s,'draw',{count:10}).ok,false);assert.equal(s.tickets,9);s.tickets=100;ok(s,'draw',{count:10});assert.equal(s.sequence,10);assert.equal(s.tickets,90);assert.equal(act(s,'draw',{count:1}).ok,false);const rs=JSON.stringify(s.pendingBatch);s=JSON.parse(JSON.stringify(s));assert.equal(JSON.stringify(s.pendingBatch),rs);ok(s,'ackBatch');s.free=1;ok(s,'draw',{free:true});assert.equal(s.sequence,11);assert.equal(s.tickets,90);});
test('1000 partitions of one sequence are equivalent; all 25 by item 120; tail remains legal',()=>{const base=start();base.tickets=300;for(let i=0;i<12;i++){ok(base,'draw',{count:10});ok(base,'ackBatch');}assert.equal(base.toys.length,25);assert.equal(FIRST_POSITIONS.at(-1),120);for(let run=0;run<1000;run++){const s=start();s.tickets=300;let left=120,seed=run+17;while(left){seed=(seed*1664525+1013904223)>>>0;const n=[1,5,10][seed%3];const count=n<=left?n:1;ok(s,'draw',{count});ok(s,'ackBatch');left-=count;}for(const k of ['energy','coins','speed','tickets','duplicate','free','sequence'])assert.equal(s[k],base[k]);assert.deepEqual(s.toys,base.toys);}for(let i=0;i<18;i++){ok(base,'draw',{count:10});ok(base,'ackBatch');}assert.equal(base.sequence,300);assert.equal(base.toys.length,25);assert.ok(base.duplicate<CONFIG.duplicateThreshold);assert.ok(base.free<300);});
test('upstream order is idempotent; offline actions fail without mutation',()=>{const s=start();assert.equal(receiveOrder(s,'order-1',80).ok,true);const e=s.energy;assert.equal(receiveOrder(s,'order-1',80).ok,false);assert.equal(s.energy,e);s.online=false;assert.equal(act(s,'node',{id:currentNode(s).id}).ok,false);assert.equal(receiveOrder(s,'order-2',80).ok,false);assert.equal(s.energy,e);});
test('natural recovery respects cap, overflow and fresh timer after spending',()=>{const t=Date.now(),s=initialState(t);s.energy=140;s.lastRegen=t;tick(s,t+20*CONFIG.regenMs);assert.equal(s.energy,150);s.energy=180;tick(s,t+30*CONFIG.regenMs);assert.equal(s.energy,180);s.energy=100;s.lastRegen=t;tick(s,t+3*CONFIG.regenMs);assert.equal(s.energy,103);});
test('expiry allows current visit, settlement clears event resources once and preserves main rewards',()=>{const s=start();s.clockOffset=14*86400000;const n=currentNode(s);ok(s,'node',{id:n.id});assert.equal(receiveOrder(s,'late',80).ok,false);s.coins=23;s.tickets=10;s.toys=[0];ok(s,'leave');assert.equal(s.ended,true);assert.equal(s.tickets,0);assert.equal(s.toys.length,0);assert.equal(s.coins,23);assert.ok(s.settlement.pendingEnergy>0);const snap=JSON.stringify(s);settle(s);assert.equal(JSON.stringify(s),snap);});
test('reset produces genuine initial state',()=>{assert.deepEqual(initialState(1000),initialState(1000));});

test('every main and side path runs bottom to top; final story is terminal',()=>{for(const m of MAPS){for(const list of [m.nodes.filter(n=>n.type!=='chest'),...m.branches]){for(let i=1;i<list.length;i++)assert.ok(sceneY(list[i])<sceneY(list[i-1]),list[i].id);}if(m.id>0)assert.equal(m.nodes.filter(n=>n.type!=='chest').at(-1).step,2);}});
test('both energy offers check balances and share limit without partial debit',()=>{const s=start();let e=s.energy;ok(s,'exchange',{offer:'small'});assert.equal(s.energy,e+40);assert.equal(s.diamonds,88);ok(s,'exchange',{offer:'large'});assert.equal(s.energy,e+140);assert.equal(s.diamonds,58);s.diamonds=11;const before=s.energy;assert.equal(act(s,'exchange',{offer:'small'}).ok,false);assert.equal(s.energy,before);assert.equal(s.diamonds,11);s.diamonds=1000;for(let i=0;i<3;i++)ok(s,'exchange',{offer:'small'});assert.equal(act(s,'exchange',{offer:'large'}).ok,false);assert.equal(act(s,'exchange',{offer:'invalid'}).ok,false);});

import {visibleNodes,guideGeometry,collectionChanges,clampZoom} from '../src/map-view.js';
test('next story preview shows every intervening obstacle and its chests without unlocking reward',()=>{const s=start();const dest=MAPS[0].nodes.find(n=>n.type==='story');const visible=visibleNodes(s);const obstacles=MAPS[0].nodes.filter(n=>n.type==='obstacle'&&n.y<dest.y);assert.deepEqual(guideGeometry(s).obstacles.map(n=>n.id),obstacles.map(n=>n.id));assert.ok(obstacles.every(n=>visible.includes(n)));const chest=visible.find(n=>n.type==='chest');assert.ok(chest);assert.equal(accessible(s,chest),false);const e=s.energy;assert.equal(act(s,'node',{id:chest.id}).ok,false);assert.equal(s.energy,e);assert.equal(visible.some(n=>n.p===17),false);});
test('reveal advances exactly to next story and keeps later segment concealed',()=>{const s=start();s.energy=20000;completeMap(s,0);ok(s,'map',{map:1});while(!s.story.includes(2)){ok(s,'node',{id:currentNode(s).id});while(s.dialog)ok(s,'dialog',{skip:true});}const g=guideGeometry(s);assert.equal(g.target.p,3);assert.ok(g.obstacles.length>0);assert.equal(visibleNodes(s).some(n=>n.p===4),false);assert.ok(visibleNodes(s).filter(n=>n.type==='chest').some(n=>n.p===2));assert.ok(visibleNodes(s).filter(n=>n.type==='chest').some(n=>n.p===3));});function advanceUntil(s,stop=()=>false){let guard=0;while(guard++<500){if(stop(s))return;if(s.dialog){ok(s,'dialog',{skip:true});continue;}const n=currentNode(s);if(!n)return;ok(s,'node',{id:n.id});}throw new Error('Unbounded progression');}
function untilHorse(s){advanceUntil(s,s=>!s.dialog&&currentNode(s)?.step===2&&s.prepared[currentNode(s).id]);}
test('budgets unchanged and all 29 collection entries have unique reachable sources',()=>{assert.equal(MANUAL_ITEMS.length,29);assert.equal(new Set(MANUAL_ITEMS.map(i=>i.id)).size,29);assert.deepEqual(TASKS.map(t=>t.total),[5,5,5,4,5,5]);assert.ok(MANUAL_ITEMS.every(i=>NODE_BY_ID[i.nodeId]));let main=0,side=0,chests=0;MAPS.forEach((m,i)=>{let budget=m.nodes.reduce((v,n)=>v+(n.segments?.reduce((a,b)=>a+b,0)||0),0);assert.equal(budget,ZONES[i].budget);assert.equal(m.nodes.reduce((a,n)=>a+(n.segments?.length||0),0),ZONES[i].ops);main+=budget;side+=m.branches.flat().reduce((a,n)=>a+(n.segments?.[0]||0),0);chests+=m.nodes.filter(n=>n.type==='chest'&&n.kind==='energy').reduce((a,n)=>a+n.amount,0);});assert.equal(main,7800);assert.equal(side,1800);assert.equal(chests,1200);});
test('full loop: automatic scenes, explicit horses, sequential installation and independent eight rewards',()=>{const s=start();s.energy=30000;advanceUntil(s);assert.equal(s.story.length,1);for(let map=1;map<=5;map++){ok(s,'map',{map});untilHorse(s);assert.equal(s.map,map);assert.equal(s.horses.length,map-1);assert.equal(s.story.length,3*map);const n=currentNode(s);assert.equal(n.step,2);const e=s.energy;ok(s,'node',{id:n.id});assert.equal(s.energy,e);assert.equal(s.story.length,1+map*3);assert.equal(s.horses.length,map);assert.equal(s.installed.length,map-1);assert.equal(act(s,'node',{id:n.id}).ok,false);if(map<5)assert.equal(act(s,'map',{map:map+1}).ok,false);if(map===5){assert.equal(completedCollections(s),6);assert.equal(s.manual.length,29);assert.equal(rewardFor(s,'story').ready,false);assert.ok(rewardFor(s,'manual-all').ready);ok(s,'claim',{id:'manual-all'});assert.equal(s.claims.length,1);for(const t of TASKS)ok(s,'claim',{id:t.id});assert.equal(s.claims.length,7);const snapshot=s.energy;assert.equal(act(s,'claim',{id:'manual-all'}).ok,false);assert.equal(s.energy,snapshot);}ok(s,'map',{map:0});while(s.dialog)ok(s,'dialog',{skip:true});assert.equal(s.installed.length,map);}assert.equal(s.story.length,17);assert.equal(s.spent,7800);ok(s,'claim',{id:'story'});assert.equal(s.claims.length,8);for(let map=1;map<=5;map++){ok(s,'map',{map});for(let branch=0;branch<2;branch++){ok(s,'branch',{branch});advanceUntil(s);ok(s,'branch',{branch:null});}}assert.equal(s.spent,9600);assert.equal(s.manual.length,29);});
test('last obstacle or pickup starts repair without submit; end dialogue waits for horse across reload',()=>{let s=start();s.energy=20000;advanceUntil(s);ok(s,'map',{map:1});advanceUntil(s,s=>s.dialog?.p===3);assert.equal(s.dialog.type,'scene');ok(s,'dialog',{skip:true});assert.ok(s.story.includes(3));assert.ok(s.manual.includes('oven'));assert.ok(s.manual.includes('oven-parts'));assert.ok(!s.completed[currentNode(s).id]);untilHorse(s);s=JSON.parse(JSON.stringify(s));resumeScene(s);assert.equal(s.horses.length,0);assert.equal(s.story.length,3);assert.ok(s.prepared[currentNode(s).id]);const before=s.manual.length;ok(s,'node',{id:currentNode(s).id});assert.equal(s.manual.length,before+1);assert.equal(s.map,1);});
test('legacy saves retain rewards and migrate collected sources without granting an unclaimed horse',()=>{const old=initialState();old.schema=1;delete old.manual;old.started=true;old.energy=700;old.map=1;old.story=[1,2,3];old.claims=['repairs'];const final=MAPS[1].nodes.find(n=>n.step===2);old.prepared[final.id]=true;const s=migrateState(old);assert.equal(s.energy,700);assert.equal(s.horses.length,0);assert.equal(s.story.length,3);assert.ok(s.manual.includes('recipe'));assert.ok(s.manual.includes('oven'));assert.equal(rewardFor(s,'region-1').ready,true);const e=s.energy;ok(s,'claim',{id:'region-1'});assert.equal(s.energy,e);assert.equal(s.legacyCredit.energy,40);const raw=JSON.stringify(old);const store={getItem:k=>k===LEGACY_SAVE_KEY?raw:null};assert.equal(loadState(store).schema,2);assert.equal(raw,JSON.stringify(old));assert.deepEqual(migrateState(s),s);});
test('manual feedback reports every new item once, with incremental collection counts',()=>{const before=start(),after=structuredClone(before);after.manual=['track-parts','spring','tracks'];assert.deepEqual(collectionChanges(before,after).map(i=>[i.task,i.count]),[['region-2',1],['region-2',2],['region-2',3]]);assert.deepEqual(collectionChanges(after,structuredClone(after)),[]);});
test('collection positioning follows missing prerequisite and reward previews never unlock sources',()=>{const s=start();s.energy=20000;advanceUntil(s);ok(s,'map',{map:1});const item=MANUAL_ITEMS.find(i=>i.id==='oven');assert.equal(collectionTarget(s,item.nodeId).id,currentNode(s).id);const before=s.energy;assert.equal(act(s,'node',{id:item.nodeId}).ok,false);assert.equal(s.energy,before);});
