import {CONFIG,sceneY,MAPS,ZONES,NODE_BY_ID,TASKS,TOYS,ITEM_BY_ID} from './config.js';
import {initialState,loadState,saveState,SAVE_KEY} from './state.js';
import {act,tick,settle,currentNode,accessible,done,collectionTarget,resumeScene,ownsItem,unlocked} from './game-engine.js';
import {receiveOrder,expired,rewardFor} from './game-engine.js';
import {gameView,welcome,modalView,dialogView,timeText,regenText,goal,resourceIcon} from './components.js';
import {icon} from './art.js';
import {clampZoom,guideGeometry,collectionChanges} from './map-view.js';
let state=loadState();resumeScene(state);
const ui={modal:null,selected:null,multiplier:1,busy:false,cost:null,rewardId:'story',zoom:clampZoom(state.settings.zoom||1),guide:false};
const app=document.querySelector('#app');let scroll=0,scrollX=0,toastTimer,busyTimer,guideToken=0,feedbackRunning=false;const feedbackQueue=[];let audioCtx,feedbackPromise=Promise.resolve(),dialogTimer,dialogKey;
if(expired(state)&&state.online)settle(state);tick(state);
if(state.pendingBatch)ui.modal='results';
function persist(){try{saveState(state);}catch{toast('本机存储不可用，关闭页面后可能无法恢复。请导出存档。');}}
function reduced(){return state.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;}
function sound(type='tap'){if(!state.settings.sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();const t=audioCtx.currentTime;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(type==='reward'?700:420,t);o.frequency.exponentialRampToValueAtTime(type==='reward'?1100:280,t+.16);g.gain.setValueAtTime(.07,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.23);}catch{}}
function render({focus=false}={}){const feedbackElements=[...app.querySelectorAll('.collection-bubble,.collection-banner')];scroll=document.querySelector('#viewport')?.scrollTop??scroll;scrollX=document.querySelector('#viewport')?.scrollLeft??scrollX;const modalScroll=document.querySelector('.panel-content')?.scrollTop||0;app.innerHTML=(!state.started||!state.inside||state.ended?welcome(state):gameView(state,ui,app.clientWidth))+(ui.modal?modalView(state,ui):'')+dialogView(state);feedbackElements.forEach(e=>app.append(e));document.body.classList.toggle('reduced',state.settings.reduced);const vp=document.querySelector('#viewport');if(vp){vp.scrollTop=scroll;vp.scrollLeft=scrollX;dragMap(vp);}const panel=document.querySelector('.panel-content');if(panel)panel.scrollTop=modalScroll;document.querySelector('#desktop-status').innerHTML=`<span>剧情 ${state.story.length} / 17</span><br><span>木马 ${state.installed.length} / 5 · 收藏 ${state.toys.length} / 25</span><br><span class="saved-indicator">本机自动存档</span>`;if(focus)requestAnimationFrame(()=>focusTarget(false));scheduleDialog();}
function open(type){ui.modal=type;ui.cost=type==='energy'?ui.cost:null;render();const c=document.querySelector('.panel-content');if(c)c.scrollTop=0;document.querySelector('.panel .close, .panel .primary')?.focus({preventScroll:true});}
function toast(text){clearTimeout(toastTimer);document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.setAttribute('role','status');t.textContent=text;app.append(t);toastTimer=setTimeout(()=>t.remove(),3200);}
function focusTarget(smooth=true,id=null){const vp=document.querySelector('#viewport');if(!vp)return;const n=id?NODE_BY_ID[id]:currentNode(state);const y=n?sceneY(n):state.map===0?450:420;vp.scrollTo({left:n?Math.max(0,n.x*app.clientWidth/450*ui.zoom-vp.clientWidth/2):vp.scrollLeft,top:Math.max(0,y*app.clientWidth/450*ui.zoom-vp.clientHeight*.62),behavior:smooth&&!reduced()?'smooth':'instant'});}
function setZoom(value,anchor=null){const vp=document.querySelector('#viewport'),world=document.querySelector('.world'),wrap=document.querySelector('.world-wrap');if(!vp||!world||ui.busy)return;cancelGuide(false);const old=ui.zoom,z=clampZoom(value),r=vp.getBoundingClientRect(),at=anchor||{x:r.width/2,y:r.height/2};const oldScale=app.clientWidth/450*old,oldLeft=Math.max(0,(vp.clientWidth-450*oldScale)/2);const wx=(vp.scrollLeft+at.x-oldLeft)/oldScale,wy=(vp.scrollTop+at.y)/oldScale;ui.zoom=z;state.settings.zoom=z;const scale=app.clientWidth/450*z,left=Math.max(0,(vp.clientWidth-450*scale)/2);world.style.transform=`scale(${scale})`;world.style.left=`${left}px`;wrap.style.width=`${Math.max(vp.clientWidth,450*scale)}px`;wrap.style.height=`${Number(world.dataset.height)*scale}px`;vp.scrollLeft=wx*scale+left-at.x;vp.scrollTop=wy*scale-at.y;scroll=vp.scrollTop;scrollX=vp.scrollLeft;document.querySelector('[data-action="zoomReset"]').textContent=`${Math.round(z*100)}%`;persist();}
function dragMap(vp){const pointers=new Map();let last=null,pinch=null,moved=false;const cancel=()=>{if(ui.guide)cancelGuide(false);};vp.onwheel=e=>{e.preventDefault();cancel();const r=vp.getBoundingClientRect();setZoom(ui.zoom*(e.deltaY>0?.91:1.09),{x:e.clientX-r.left,y:e.clientY-r.top});};vp.onpointerdown=e=>{if(ui.busy||state.dialog||ui.modal)return;cancel();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});last={x:e.clientX,y:e.clientY};moved=false;if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:ui.zoom};moved=true;}};vp.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()],r=vp.getBoundingClientRect();setZoom(pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance),{x:(a.x+b.x)/2-r.left,y:(a.y+b.y)/2-r.top});moved=true;}else if(last){const dx=e.clientX-last.x,dy=e.clientY-last.y;if(Math.abs(dx)+Math.abs(dy)>3||moved){moved=true;try{vp.setPointerCapture(e.pointerId);}catch{}vp.scrollLeft-=dx;vp.scrollTop-=dy;}last={x:e.clientX,y:e.clientY};}};const end=e=>{pointers.delete(e.pointerId);pinch=null;last=pointers.size?[...pointers.values()][0]:null;if(moved){vp.dataset.dragged='1';setTimeout(()=>delete vp.dataset.dragged,120);}if(!pointers.size)moved=false;};vp.onpointerup=end;vp.onpointercancel=end;}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function cancelGuide(restore=true){if(!ui.guide)return;guideToken++;ui.guide=false;ui.guideReveal=false;document.querySelector('.route-map')?.remove();document.querySelector('.route-caption')?.remove();if(restore)render();else {const holder=document.createElement('div');holder.innerHTML=gameView(state,ui,app.clientWidth);const bubble=holder.querySelector('.map-node.current .cost-bubble');if(bubble)document.querySelector('.map-node.current')?.append(bubble);}}
function cameraTo(point,ms,token){const vp=document.querySelector('#viewport');if(!vp||token!==guideToken)return Promise.resolve();const scale=app.clientWidth/450*ui.zoom,left=Math.max(0,(vp.clientWidth-450*scale)/2);const x=Math.max(0,Math.min(vp.scrollWidth-vp.clientWidth,point.x*scale+left-vp.clientWidth/2)),y=Math.max(0,Math.min(vp.scrollHeight-vp.clientHeight,point.y*scale-vp.clientHeight*.47));const sx=vp.scrollLeft,sy=vp.scrollTop,t=performance.now();return new Promise(resolve=>{function frame(now){if(token!==guideToken||!vp.isConnected)return resolve();const k=ms?Math.min(1,(now-t)/ms):1,e=k*k*(3-2*k);vp.scrollLeft=sx+(x-sx)*e;vp.scrollTop=sy+(y-sy)*e;if(k<1)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});}
async function playRoute({reveal=false,origin=null}={}){await feedbackPromise;if(state.dialog||state.pendingBatch||ui.busy)return;cancelGuide(false);const g=guideGeometry(state);if(!g.target){if(state.map===0){ui.modal=null;render();const m=Math.min(5,state.installed.length+1),door=document.querySelector(`.scene-door[data-map="${m}"]`);door?.scrollIntoView({behavior:reduced()?'instant':'smooth',block:'center'});if(reveal)toast('新的路径已揭开 · 点击场景传送门');}else toast('木马已入册 · 可先领奖，再通过返回门回广场');return;}ui.modal=null;ui.selected=null;ui.guide=true;ui.guideReveal=reveal;const token=++guideToken,cur=currentNode(state);const home=cur?{x:cur.x,y:sceneY(cur)+60}:(origin||{x:225,y:sceneY(g.target)+160});render();try{if(reveal)await delay(reduced()?0:480);if(token!==guideToken)return;await cameraTo({x:g.target.x,y:sceneY(g.target)},reduced()?0:580,token);if(token!==guideToken)return;document.querySelector('#route-status').textContent=`${g.target.name} · 沿标记返回`;await delay(reduced()?180:550);for(const n of [...g.obstacles].reverse()){if(token!==guideToken)return;document.querySelectorAll('.route-waypoint.active').forEach(e=>e.classList.remove('active'));document.querySelector(`[data-waypoint="${n.id}"]`)?.classList.add('active');if(!reduced()){await cameraTo({x:n.x,y:sceneY(n)},140,token);await delay(60);}}await cameraTo(home,reduced()?0:340,token);}finally{if(token===guideToken){ui.guide=false;ui.guideReveal=false;render();}}}
function queueCollection(items,from){for(const item of items)feedbackQueue.push({...item,from});if(!feedbackRunning)feedbackPromise=showCollectionQueue();return feedbackPromise;}
async function showCollectionQueue(){feedbackRunning=true;while(feedbackQueue.length){const item=feedbackQueue.shift(),d=sourceInfo(item.task,item.id),task=TASKS.find(t=>t.id===item.task);document.querySelectorAll('.collection-bubble,.collection-banner').forEach(e=>e.remove());const bubble=document.createElement('div');bubble.className='collection-bubble';bubble.setAttribute('role','status');bubble.innerHTML=`${icon(d.icon)}<span>${d.title}<b class="single-count">0 / 1</b></span>`;const banner=document.createElement('div');banner.className='collection-banner';banner.innerHTML=`${icon(d.icon)}<div><small>收集任务有新进展</small><b>${task.title}</b><div class="collection-mini-track"><i style="width:${(item.count-1)/task.total*100}%"></i></div></div><strong>${item.count}/${task.total}</strong>`;app.append(bubble,banner);const book=document.querySelector('[data-action="notebook"]'),r=book?.getBoundingClientRect(),a=app.getBoundingClientRect();if(r)bubble.style.left=`${Math.max(10,Math.min(app.clientWidth-200,r.x-a.x+r.width/2-95))}px`;await fly(d.icon,item.from||center(app),center(book));if(!bubble.isConnected)continue;bubble.querySelector('.single-count').textContent='1 / 1';banner.querySelector('i').style.width=`${item.count/task.total*100}%`;if(item.count===task.total)banner.querySelector('small').textContent='收集完成 · 可前往手册领奖';await delay(reduced()?1600:2400);bubble.remove();banner.remove();}feedbackRunning=false;}
function center(el){const b=el?.getBoundingClientRect();return b?{x:b.x+b.width/2,y:b.y+b.height/2}:null;}
function fly(name,from,to,delay=0){if(!from||!to||reduced())return Promise.resolve();const f=document.createElement('div');f.className='fly';f.innerHTML=icon(name);f.style.left=`${from.x-19}px`;f.style.top=`${from.y-19}px`;document.querySelector('#fx').append(f);const a=f.animate([{transform:'translate(0,0) scale(.6)',opacity:1},{transform:`translate(${(to.x-from.x)*.45}px,${(to.y-from.y)*.45-55}px) scale(1.15)`,opacity:1},{transform:`translate(${to.x-from.x}px,${to.y-from.y}px) scale(.8)`,opacity:1}],{duration:650,delay,easing:'cubic-bezier(.2,.7,.3,1)',fill:'both'});return a.finished.catch(()=>{}).then(()=>f.remove());}
function burst(point){if(!point||reduced())return;for(let i=0;i<22;i++){const f=document.createElement('i');f.className='confetti';f.style.cssText=`left:${point.x}px;top:${point.y}px;--dx:${(Math.random()-.5)*260}px;--dy:${Math.random()*160-160}px;--color:${['#ead29b','#a5c6ad','#d3a2b6','#eee8ce'][i%4]}`;document.querySelector('#fx').append(f);setTimeout(()=>f.remove(),1400);}}
function costFx(point,cost){if(!point||reduced())return;const f=document.createElement('span');f.className='float-cost';f.style.left=`${point.x}px`;f.style.top=`${point.y-25}px`;f.textContent=`−${cost}`;document.querySelector('#fx').append(f);setTimeout(()=>f.remove(),900);}
function execute(action,data={}){const snapshot=structuredClone(state);let r;try{r=act(state,action,data);if(r.ok){saveState(state);sound(r.reward?'reward':'tap');}return r;}catch(e){state=snapshot;return {ok:false,message:'保存失败，未提交本次操作。请导出已有存档。'};}}
function handleResult(r){if(!r.ok){if(r.needEnergy){ui.cost=r.cost;open('energy');}toast(r.message);return false;}if(r.reward){ui.reward=r.reward;open('reward');}if(r.message)toast(r.message);return true;}
async function transitionMap(map){if(ui.busy)return;ui.busy=true;const veil=document.createElement('div');veil.className='loading';veil.innerHTML=`<div class="spinner"></div><span>前往${ZONES[map].name}</span>`;app.append(veil);await new Promise(r=>setTimeout(r,reduced()?0:420));const r=execute('map',{map});ui.busy=false;if(!r.ok){veil.remove();toast(r.message);return;}ui.modal=null;ui.selected=null;scroll=0;scrollX=0;render({focus:true});await delay(100);await playRoute({reveal:true});}
async function draw(free){const r=execute('draw',{count:ui.multiplier,free});if(!r.ok){toast(r.message);return;}ui.busy=true;render();const source=center(document.querySelector('.panel #outlet'));await new Promise(r=>setTimeout(r,reduced()?0:700));ui.busy=false;ui.modal='results';render();const cards=[...document.querySelectorAll('[data-result]')];cards.forEach(c=>c.style.visibility=reduced()?'visible':'hidden');await Promise.all(r.results.map((item,i)=>fly(item.type==='toy'?TOYS[item.id].icon:resourceIcon(item.type),source,center(cards[i]),i*75).then(()=>{if(cards[i])cards[i].style.visibility='visible';})));sound('reward');}
function sourceInfo(task,id){const item=ITEM_BY_ID[id];return {...item,title:item.name,id:item.nodeId,itemId:item.id,branch:null,text:item.kind==='horse'?`在${ZONES[item.map].name}最终对白后点击领取，回广场自动安装。`:item.kind==='scene'?'清开道路、收齐本点道具后自动点亮，场景建筑保留。':'沿主路清障后免费拾取。'};}
function locateCollection(d){if(ownsItem(state,d.itemId)){toast(`${d.title}已收集${d.kind==='horse'&&!state.installed.includes(d.map)?' · 返回中央广场安装':''}`);return;}if(d.map!==state.map){toast(unlocked(state,d.map)?`前往${ZONES[d.map].name}收集`:`${ZONES[d.map].name}解锁后可收集`);return;}const n=collectionTarget(state,d.id);if(!n)return toast('暂时无法定位该收藏');const branch=n.branch??null;if(branch!==state.branch){const r=execute('branch',{branch});if(!r.ok)return toast(r.message);}ui.modal=null;ui.selected=n.id;render();focusTarget(true,n.id);const stage=state.stages[n.id]||0;toast(done(state,d.id)?`${d.title}已收集`:n.type==='obstacle'?`先清开${n.name} · 剩余${n.segments.length-stage}段`:`已定位：${n.name}`);}
function fastForward(){if(!state.inside||state.ended||state.dialog||state.pendingBatch)return toast('请先回到地图，完成当前剧情或扭蛋结果');let n=currentNode(state),count=0;if(!n)return toast('此处已没有待推进的主路目标');while(n&&!state.dialog&&n.type!=='story'&&count<150){if(n.type==='obstacle'&&state.energy<n.segments[state.stages[n.id]||0]){state.energy+=1000;state.events.push({type:'debug_supply',amount:1000,at:Date.now()});}const r=act(state,'node',{id:n.id});if(!r.ok)return toast(r.message);n=currentNode(state);count++;}persist();ui.modal=null;ui.selected=null;render({focus:true});toast(`评审推进了 ${count} 次操作；请继续当前剧情或拾取目标`);}
async function progressDialog(skip=false){const doorsBefore=ZONES.map((_,i)=>unlocked(state,i));const old=state.story.length,beforeCollections=structuredClone(state),origin=currentNode(state);const r=execute('dialog',{skip:skip});ui.revealDoor=ZONES.findIndex((_,i)=>!doorsBefore[i]&&unlocked(state,i));render();setTimeout(()=>{ui.revealDoor=null;},1800);if(!r.ok)return toast(r.message);const collected=collectionChanges(beforeCollections,state);if(collected.length)queueCollection(collected,center(app));if(r.finale){ui.modal='finale';render();burst(center(app));}else if(r.horseReady){focusTarget();toast(r.message);}else if(r.installed){await playRoute({reveal:true});}else if(r.horse){burst(center(app));toast(r.message);}else if(state.story.length>old){toast(`剧情进度 +1 · ${state.story.length}/17，宝箱已经出现`);await playRoute({reveal:true,origin:origin?{x:origin.x,y:sceneY(origin)+60}:null});}}
function scheduleDialog(){const key=state.dialog?`${state.dialog.type}:${state.dialog.map}:${state.dialog.p}:${state.dialog.index}`:null;if(key===dialogKey)return;dialogKey=key;clearTimeout(dialogTimer);if(!key)return;dialogTimer=setTimeout(async()=>{await feedbackPromise;if(dialogKey===key&&state.online)await progressDialog(false);else if(!state.online){dialogKey=null;scheduleDialog();}},5000);}
app.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||document.querySelector('#viewport')?.dataset.dragged)return;const a=b.dataset.action;if(a==='cancelGuide'){cancelGuide();return;}if(ui.guide&&!['zoomIn','zoomOut','zoomReset'].includes(a))return;if(ui.busy)return;if(state.dialog&&!['dialog','skipDialog'].includes(a))return;
 if(a==='zoomIn'||a==='zoomOut'||a==='zoomReset'){setZoom(a==='zoomReset'?1:ui.zoom+(a==='zoomIn'?.15:-.15));return;}
 if(a==='route'){await playRoute();return;}
 if(a==='rewardPreview'){const n=NODE_BY_ID[b.dataset.id];toast(`${n.name} +${n.amount} · 完成对应剧情后可领取`);return;}
 if(a==='start'){execute('start');ui.modal=null;render({focus:true});return;}
 if(a==='node'){const n=NODE_BY_ID[b.dataset.id];const pt=center(b),beforeStory=state.story.length,beforeCollections=structuredClone(state);const r=execute('node',{id:n.id});if(!r.ok){handleResult(r);return;}ui.selected=r.cleared?null:n.id;render();const collected=collectionChanges(beforeCollections,state);if(collected.length)queueCollection(collected,pt);if(r.cost)costFx(pt,r.cost);if(r.cleared){ui.busy=true;await new Promise(res=>setTimeout(res,reduced()?0:260));ui.busy=false;focusTarget();}if(r.reward)fly(resourceIcon(Object.keys(r.reward)[0]),pt,center(document.querySelector('.energy-pill')));if(r.drop)fly('ticket',pt,center(document.querySelector('[data-action="gacha"]')));if(r.horse)burst(pt);if(state.story.length>beforeStory){toast(`剧情进度 +1 · ${state.story.length}/17，附近宝箱已解锁`);burst(pt);await playRoute({reveal:true,origin:{x:n.x,y:sceneY(n)+60}});}else if(r.message)toast(r.message);else if(r.reward)toast(Object.entries(r.reward).map(([k,v])=>`${k==='energy'?'活动体力':'金币'} +${v}`).join(' '));return;}
 if(a==='dialog'||a==='skipDialog'){await progressDialog(a==='skipDialog');return;}
 if(a==='lockedDoor'){const map=Number(b.dataset.map);toast(map===1?'先到旋转木马前完成开场':`请先回广场安装${ZONES[map-1].horse}`);return;}
 if(a==='close'){if(state.pendingBatch)return;ui.modal=null;render();return;}
 if(a==='map'){await transitionMap(Number(b.dataset.map));return;}
 if(a==='portal'){if(state.branch!==null){handleResult(execute('branch',{branch:null}));scroll=0;ui.selected=null;render({focus:true});}else if(state.map)await transitionMap(0);else open('maps');return;}
 if(a==='branch'){const r=execute('branch',{branch:Number(b.dataset.branch)});if(handleResult(r)){scroll=0;ui.selected=null;render({focus:true});}return;}
 if(a==='locate'){const g=goal(state);if(g.portal){ui.modal=null;render();if(state.map===0)await playRoute();else {document.querySelector('[data-action="portal"]')?.focus({preventScroll:true});toast('点击右下方返回门，自行回广场安装');}}else{await playRoute();}return;}
 if(a==='source'){locateCollection(sourceInfo(b.dataset.task,b.dataset.id));return;}
 if(a==='taskLocate'){const task=b.dataset.task;const ids=TASKS.find(t=>t.id===task).items.map(i=>i.id);const id=ids.find(id=>!ownsItem(state,id))??ids[0];locateCollection(sourceInfo(task,id));return;}
 if(a==='locateSource'){locateCollection(ui.source);return;}
 if(a==='toy'){ui.toy=Number(b.dataset.id);execute('viewToy',{id:ui.toy});open('toy');return;}
 if(a==='multiplier'){ui.multiplier=Number(b.dataset.count);render();return;}
 if(a==='draw'||a==='free'){await draw(a==='free');return;}
 if(a==='ackBatch'){const r=execute('ackBatch');if(!r.ok)return toast(r.message);open('gacha');return;}
 if(a==='claim'){handleResult(execute('claim',{id:b.dataset.id}));return;}
 if(a==='preview'){ui.rewardId=b.dataset.id;open('preview');return;}
 if(a==='prize'){ui.rewardId='story';open('prize');return;}
 if(a==='exchange'){handleResult(execute('exchange',{offer:b.dataset.offer}));return;}
 if(a==='leave'){const r=execute('leave');if(!r.ok)return toast(r.message);ui.modal=state.ended?'settlement':null;feedbackQueue.length=0;document.querySelectorAll('.collection-bubble,.collection-banner').forEach(e=>e.remove());render();return;}
 if(a==='enter'){const r=execute('enter');if(!r.ok)return toast(r.message);ui.modal=null;render({focus:true});return;}
 if(a==='sound'||a==='reduced'){state.settings[a]=!state.settings[a];persist();render();sound();return;}
 if(a==='network'){state.online=!state.online;persist();render();return;}
 if(a==='order'){const val=document.querySelector('#order-amount')?.value??state.review.orderEnergy;const amount=Number(val);const r=receiveOrder(state,`review-${Date.now()}-${state.orders.length}`,amount);if(r.ok){persist();render();toast(`模拟订单已完成 · 活动体力 +${amount}`);}else toast(r.message);return;}
 if(a==='saveConfig'){const amount=Number(document.querySelector('#order-amount').value),raw=document.querySelector('#conversion').value,rate=raw===''?null:Number(raw);if(!Number.isSafeInteger(amount)||amount<0||amount>100000||rate!==null&&(!Number.isFinite(rate)||rate<0||rate>10000))return toast('请输入有效的非负体验数值');state.review={orderEnergy:amount,energyConversion:rate};persist();toast('体验配置已保存');return;}
 if(a==='advanceTime'){state.clockOffset+=6*3600000;tick(state);persist();render();toast('评审时间推进 6 小时，恢复按上限计算');return;}
 if(a==='expire'){state.clockOffset=14*86400000;tick(state);persist();render();toast('已到期：停留活动可续玩，离开后结算');return;}
 if(a==='zeroEnergy'){state.energy=0;state.lastRegen=Date.now()+state.clockOffset;persist();render();return;}
 if(a==='addTickets'){state.tickets+=100;state.events.push({type:'debug_tickets',amount:100,at:Date.now()});persist();render();return;}
 if(a==='fastForward'){fastForward();return;}
 if(a==='reset'){state=initialState();ui.modal=null;ui.selected=null;ui.multiplier=1;ui.zoom=1;scroll=0;scrollX=0;feedbackQueue.length=0;document.querySelectorAll('.collection-bubble,.collection-banner').forEach(e=>e.remove());persist();render();return;}
 if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='梦境博览会-体验存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
 open(a);
});
document.querySelector('#review-entry').addEventListener('click',()=>{if(ui.busy||state.dialog||state.pendingBatch)return toast('请先完成当前演出');open('review');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&ui.guide){cancelGuide();return;}if(e.key==='Escape'&&ui.modal&&!state.pendingBatch&&!ui.busy){ui.modal=null;render();}});
new ResizeObserver(()=>render()).observe(app);
window.addEventListener('pagehide',persist);
setInterval(()=>{const before=state.energy;tick(state);if(before!==state.energy)persist();const en=document.querySelector('#energy-value'),rg=document.querySelector('#regen'),cl=document.querySelector('#clock');if(en)en.textContent=`${state.energy}/150`;if(rg)rg.textContent=regenText(state);if(cl)cl.textContent=`◷ ${timeText(state)}`;},1000);
render({focus:true});persist();
