import {CONFIG,sceneY,MAPS,ZONES,NODE_BY_ID,TASKS,TOYS} from './config.js';
import {initialState,loadState,saveState,SAVE_KEY} from './state.js';
import {act,tick,settle,currentNode,accessible,done,collectionTarget,migrateHorse} from './game-engine.js';
import {receiveOrder,expired,rewardFor} from './game-engine.js';
import {gameView,welcome,modalView,dialogView,timeText,regenText,goal,resourceIcon} from './components.js';
import {icon} from './art.js';
let state=loadState();migrateHorse(state);
const ui={modal:null,selected:null,multiplier:1,busy:false,cost:null,rewardId:'story'};
const app=document.querySelector('#app');let scroll=0,toastTimer,busyTimer;let audioCtx;
if(expired(state)&&state.online)settle(state);tick(state);
if(state.pendingBatch)ui.modal='results';
function persist(){try{saveState(state);}catch{toast('本机存储不可用，关闭页面后可能无法恢复。请导出存档。');}}
function reduced(){return state.settings.reduced||matchMedia('(prefers-reduced-motion: reduce)').matches;}
function sound(type='tap'){if(!state.settings.sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();const t=audioCtx.currentTime;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(type==='reward'?700:420,t);o.frequency.exponentialRampToValueAtTime(type==='reward'?1100:280,t+.16);g.gain.setValueAtTime(.07,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.23);}catch{}}
function render({focus=false}={}){scroll=document.querySelector('#viewport')?.scrollTop??scroll;const modalScroll=document.querySelector('.panel-content')?.scrollTop||0;app.innerHTML=(!state.started||!state.inside||state.ended?welcome(state):gameView(state,ui,app.clientWidth))+(ui.modal?modalView(state,ui):'')+dialogView(state);document.body.classList.toggle('reduced',state.settings.reduced);const vp=document.querySelector('#viewport');if(vp){vp.scrollTop=scroll;dragMap(vp);}const panel=document.querySelector('.panel-content');if(panel)panel.scrollTop=modalScroll;document.querySelector('#desktop-status').innerHTML=`<span>剧情 ${state.story.length} / 17</span><br><span>木马 ${state.installed.length} / 5 · 收藏 ${state.toys.length} / 25</span><br><span class="saved-indicator">本机自动存档</span>`;if(focus)requestAnimationFrame(()=>focusTarget(false));}
function open(type){ui.modal=type;ui.cost=type==='energy'?ui.cost:null;render();const c=document.querySelector('.panel-content');if(c)c.scrollTop=0;document.querySelector('.panel .close, .panel .primary')?.focus({preventScroll:true});}
function toast(text){clearTimeout(toastTimer);document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className='toast';t.setAttribute('role','status');t.textContent=text;app.append(t);toastTimer=setTimeout(()=>t.remove(),3200);}
function focusTarget(smooth=true,id=null){const vp=document.querySelector('#viewport');if(!vp)return;const n=id?NODE_BY_ID[id]:currentNode(state);const y=n?sceneY(n):state.map===0?450:420;vp.scrollTo({top:Math.max(0,y*app.clientWidth/450-vp.clientHeight*.62),behavior:smooth&&!reduced()?'smooth':'instant'});}
function dragMap(vp){let start=null,moved=false;vp.onpointerdown=e=>{if(e.pointerType!=='mouse')return;start={y:e.clientY,scroll:vp.scrollTop};moved=false;};vp.onpointermove=e=>{if(!start||e.buttons!==1)return;if(Math.abs(e.clientY-start.y)>7)moved=true;if(moved){vp.scrollTop=start.scroll-(e.clientY-start.y);}};vp.onpointerup=()=>{start=null;if(moved){vp.dataset.dragged='1';setTimeout(()=>delete vp.dataset.dragged,80);}};vp.onpointerleave=()=>{start=null;};}
function center(el){const b=el?.getBoundingClientRect();return b?{x:b.x+b.width/2,y:b.y+b.height/2}:null;}
function fly(name,from,to,delay=0){if(!from||!to||reduced())return Promise.resolve();const f=document.createElement('div');f.className='fly';f.innerHTML=icon(name);f.style.left=`${from.x-19}px`;f.style.top=`${from.y-19}px`;document.querySelector('#fx').append(f);const a=f.animate([{transform:'translate(0,0) scale(.6)',opacity:1},{transform:`translate(${(to.x-from.x)*.45}px,${(to.y-from.y)*.45-55}px) scale(1.15)`,opacity:1},{transform:`translate(${to.x-from.x}px,${to.y-from.y}px) scale(.8)`,opacity:1}],{duration:650,delay,easing:'cubic-bezier(.2,.7,.3,1)',fill:'both'});return a.finished.catch(()=>{}).then(()=>f.remove());}
function burst(point){if(!point||reduced())return;for(let i=0;i<22;i++){const f=document.createElement('i');f.className='confetti';f.style.cssText=`left:${point.x}px;top:${point.y}px;--dx:${(Math.random()-.5)*260}px;--dy:${Math.random()*160-160}px;--color:${['#ead29b','#a5c6ad','#d3a2b6','#eee8ce'][i%4]}`;document.querySelector('#fx').append(f);setTimeout(()=>f.remove(),1400);}}
function costFx(point,cost){if(!point||reduced())return;const f=document.createElement('span');f.className='float-cost';f.style.left=`${point.x}px`;f.style.top=`${point.y-25}px`;f.textContent=`−${cost}`;document.querySelector('#fx').append(f);setTimeout(()=>f.remove(),900);}
function execute(action,data={}){const snapshot=structuredClone(state);let r;try{r=act(state,action,data);if(r.ok){saveState(state);sound(r.reward?'reward':'tap');}return r;}catch(e){state=snapshot;return {ok:false,message:'保存失败，未提交本次操作。请导出已有存档。'};}}
function handleResult(r){if(!r.ok){if(r.needEnergy){ui.cost=r.cost;open('energy');}toast(r.message);return false;}if(r.reward){ui.reward=r.reward;open('reward');}if(r.message)toast(r.message);return true;}
async function transitionMap(map){if(ui.busy)return;ui.busy=true;const veil=document.createElement('div');veil.className='loading';veil.innerHTML=`<div class="spinner"></div><span>前往${ZONES[map].name}</span>`;app.append(veil);await new Promise(r=>setTimeout(r,reduced()?0:420));const r=execute('map',{map});ui.busy=false;if(!r.ok){veil.remove();toast(r.message);return;}ui.modal=null;ui.selected=null;scroll=0;render({focus:true});}
async function draw(free){const r=execute('draw',{count:ui.multiplier,free});if(!r.ok){toast(r.message);return;}ui.busy=true;render();const source=center(document.querySelector('.panel #outlet'));await new Promise(r=>setTimeout(r,reduced()?0:700));ui.busy=false;ui.modal='results';render();const cards=[...document.querySelectorAll('[data-result]')];cards.forEach(c=>c.style.visibility=reduced()?'visible':'hidden');await Promise.all(r.results.map((item,i)=>fly(item.type==='toy'?TOYS[item.id].icon:resourceIcon(item.type),source,center(cards[i]),i*75).then(()=>{if(cards[i])cards[i].style.visibility='visible';})));sound('reward');}
function sourceInfo(task,id){if(task==='mementos'){const n=NODE_BY_ID[id];return {title:n.name,icon:n.icon,map:n.map,branch:n.branch,id:n.id,text:`在${ZONES[n.map].name}的回忆小径 ${n.branch+1}，清开道路后免费拾取。`};}const map=Number(id),z=ZONES[map],step=task==='horses'?2:1;return {title:task==='horses'?z.horse:`${z.repair}纪念标记`,icon:task==='horses'?'horse':z.icon,map,branch:null,id:MAPS[map].nodes.find(n=>n.type==='story'&&n.step===step).id,text:task==='horses'?`在${z.name}完成最终剧情后自动获得。获得后保留在手册，自行回广场安装。`:`在${z.name}修复${z.repair}后，再次点击纪念标记收集。`};}
function locateCollection(d){if(d.map!==state.map){toast(`在${ZONES[d.map].name}区域解锁`);return;}const n=collectionTarget(state,d.id);if(!n)return toast('暂时无法定位该收藏');const branch=n.branch??null;if(branch!==state.branch){const r=execute('branch',{branch});if(!r.ok)return toast(r.message);}ui.modal=null;ui.selected=n.id;render();focusTarget(true,n.id);const stage=state.stages[n.id]||0;toast(done(state,d.id)?`${d.title}已收集`:n.type==='obstacle'?`先清开${n.name} · 剩余${n.segments.length-stage}段`:`已定位：${n.name}`);}
function fastForward(){if(!state.inside||state.ended||state.dialog||state.pendingBatch)return toast('请先回到地图，完成当前剧情或扭蛋结果');let n=currentNode(state),count=0;if(!n)return toast('此处已没有待推进的主路目标');while(n&&n.type!=='story'&&count<150){if(n.type==='obstacle'&&state.energy<n.segments[state.stages[n.id]||0]){state.energy+=1000;state.events.push({type:'debug_supply',amount:1000,at:Date.now()});}const r=act(state,'node',{id:n.id});if(!r.ok)return toast(r.message);n=currentNode(state);count++;}persist();ui.modal=null;ui.selected=null;render({focus:true});toast(`评审推进了 ${count} 次操作；剧情仍需手动完成`);}
app.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||document.querySelector('#viewport')?.dataset.dragged)return;const a=b.dataset.action;if(ui.busy)return;if(state.dialog&&!['dialog','skipDialog'].includes(a))return;
 if(a==='start'){execute('start');ui.modal=null;render({focus:true});return;}
 if(a==='node'){const n=NODE_BY_ID[b.dataset.id];if(n.type==='obstacle'&&ui.selected!==n.id){ui.selected=n.id;render();return;}const pt=center(b),beforeStory=state.story.length;const r=execute('node',{id:n.id});if(!r.ok){handleResult(r);return;}ui.selected=r.cleared?null:n.id;render();if(r.cost)costFx(pt,r.cost);if(r.cleared){ui.busy=true;await new Promise(res=>setTimeout(res,reduced()?0:260));ui.busy=false;focusTarget();}if(r.reward)fly(resourceIcon(Object.keys(r.reward)[0]),pt,center(document.querySelector('.energy-pill')));if(r.drop)fly('ticket',pt,center(document.querySelector('[data-action="gacha"]')));if(r.horse){fly('horse',pt,center(document.querySelector('[data-action="notebook"]')));burst(pt);}if(state.story.length>beforeStory){toast(`剧情进度 +1 · ${state.story.length}/17，附近宝箱已解锁`);burst(pt);}else if(r.message)toast(r.message);else if(r.reward)toast(Object.entries(r.reward).map(([k,v])=>`${k==='energy'?'活动体力':'金币'} +${v}`).join(' '));return;}
 if(a==='dialog'||a==='skipDialog'){const old=state.story.length;const r=execute('dialog',{skip:a==='skipDialog'});render();if(!r.ok)return toast(r.message);if(r.finale){ui.modal='finale';render();burst(center(app));}else if(r.horse){fly('horse',center(app),center(document.querySelector('[data-action="notebook"]')));burst(center(app));toast(r.message);}else if(state.story.length>old){toast(`剧情进度 +1 · ${state.story.length}/17，宝箱已经出现`);}return;}
 if(a==='close'){if(state.pendingBatch)return;ui.modal=null;render();return;}
 if(a==='map'){await transitionMap(Number(b.dataset.map));return;}
 if(a==='portal'){if(state.branch!==null){handleResult(execute('branch',{branch:null}));scroll=0;ui.selected=null;render({focus:true});}else if(state.map)await transitionMap(0);else open('maps');return;}
 if(a==='branch'){const r=execute('branch',{branch:Number(b.dataset.branch)});if(handleResult(r)){scroll=0;ui.selected=null;render({focus:true});}return;}
 if(a==='locate'){const g=goal(state);if(g.portal){open('maps');}else{ui.modal=null;render();focusTarget();}return;}
 if(a==='source'){locateCollection(sourceInfo(b.dataset.task,b.dataset.id));return;}
 if(a==='taskLocate'){const task=b.dataset.task;const ids=task==='mementos'?MAPS.flatMap(m=>m.branches.flat()).filter(n=>n.type==='memento').map(n=>n.id):[1,2,3,4,5];const id=ids.find(id=>!state[task].includes(id))??ids[0];locateCollection(sourceInfo(task,id));return;}
 if(a==='locateSource'){locateCollection(ui.source);return;}
 if(a==='toy'){ui.toy=Number(b.dataset.id);execute('viewToy',{id:ui.toy});open('toy');return;}
 if(a==='multiplier'){ui.multiplier=Number(b.dataset.count);render();return;}
 if(a==='draw'||a==='free'){await draw(a==='free');return;}
 if(a==='ackBatch'){const r=execute('ackBatch');if(!r.ok)return toast(r.message);open('gacha');return;}
 if(a==='claim'){handleResult(execute('claim',{id:b.dataset.id}));return;}
 if(a==='preview'){ui.rewardId=b.dataset.id;open('preview');return;}
 if(a==='prize'){ui.rewardId='story';open('prize');return;}
 if(a==='exchange'){handleResult(execute('exchange',{offer:b.dataset.offer}));return;}
 if(a==='leave'){const r=execute('leave');if(!r.ok)return toast(r.message);ui.modal=state.ended?'settlement':null;render();return;}
 if(a==='enter'){const r=execute('enter');if(!r.ok)return toast(r.message);ui.modal=null;render({focus:true});return;}
 if(a==='sound'||a==='reduced'){state.settings[a]=!state.settings[a];persist();render();sound();return;}
 if(a==='network'){state.online=!state.online;persist();render();return;}
 if(a==='order'){const val=document.querySelector('#order-amount')?.value??state.review.orderEnergy;const amount=Number(val);const r=receiveOrder(state,`review-${Date.now()}-${state.orders.length}`,amount);if(r.ok){persist();render();toast(`模拟订单已完成 · 活动体力 +${amount}`);}else toast(r.message);return;}
 if(a==='saveConfig'){const amount=Number(document.querySelector('#order-amount').value),raw=document.querySelector('#conversion').value,rate=raw===''?null:Number(raw);if(!Number.isSafeInteger(amount)||amount<0||amount>100000||rate!==null&&(!Number.isFinite(rate)||rate<0||rate>10000))return toast('请输入有效的非负体验数值');state.review={orderEnergy:amount,energyConversion:rate};persist();toast('体验配置已保存');return;}
 if(a==='advanceTime'){state.clockOffset+=6*3600000;tick(state);persist();render();toast('评审时间推进 6 小时，恢复按上限计算');return;}
 if(a==='expire'){state.clockOffset=14*86400000;tick(state);persist();render();toast('已到期：停留活动可续玩，离开后结算');return;}
 if(a==='zeroEnergy'){state.energy=0;state.lastRegen=Date.now()+state.clockOffset;persist();render();return;}
 if(a==='addTickets'){state.tickets+=100;state.events.push({type:'debug_tickets',amount:100,at:Date.now()});persist();render();return;}
 if(a==='fastForward'){fastForward();return;}
 if(a==='reset'){state=initialState();ui.modal=null;ui.selected=null;ui.multiplier=1;scroll=0;persist();render();return;}
 if(a==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='梦境博览会-体验存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
 open(a);
});
document.querySelector('#review-entry').addEventListener('click',()=>{if(ui.busy||state.dialog||state.pendingBatch)return toast('请先完成当前演出');open('review');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&ui.modal&&!state.pendingBatch&&!ui.busy){ui.modal=null;render();}});
new ResizeObserver(()=>render()).observe(app);
window.addEventListener('pagehide',persist);
setInterval(()=>{const before=state.energy;tick(state);if(before!==state.energy)persist();const en=document.querySelector('#energy-value'),rg=document.querySelector('#regen'),cl=document.querySelector('#clock');if(en)en.textContent=`${state.energy}/150`;if(rg)rg.textContent=regenText(state);if(cl)cl.textContent=`◷ ${timeText(state)}`;},1000);
render({focus:true});persist();
